### ISSUE TITLE
TemplateDoesNotExist error.

### ISSUE THREAD

**Issue by ss12344** [individuo7/django-dashing-demo-app#2]
using this out of the box doesn't work dyjango complains it cannot find the template dashboard.html. The settings.py has the following declared:

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'templates'),
)

This would work if there was a templates dir in the dir of the projects along with the dashboard.html. I couldn't get this example to work out of the box even with some faffing. It looks like there a change made where the templates dir is missing and the respective.html file. 

If this isn't broken can there be the appropriate documentation provided on how one can use the example? 

Thanks.

**Comment by mtdb** [comment]
solved
